SEEDS = [
    "political framework",
    "political party",
    "electoral procedure and voting",
    "parliament",
    "parliamentary proceedings",
    "politics and public safety",
    "international affairs",
    "cooperation policy",
    "international balance",
    "defence",
    "European construction",
    "European Union law",
    "EU institutions and European civil service",
    "EU finance",
    "EU policies",
    "sources and branches of law",
    "civil law",
    "criminal law",
    "justice",
    "organisation of the legal system",
    "international law",
    "rights and freedoms",
    "economic policy",
    "economic structure",
    "regions and regional policy",
    "economic geography",
    "economic analysis",
    "economic statistics",
    "accounting",
    "trade policy",
    "tariff policy",
    "trade",
    "international trade",
    "consumption",
    "marketing",
    "distributive trades",
    "monetary economics",
    "financial institutions and credit",
    "free movement of capital",
    "financing and investment",
    "public finance and budget policy",
    "budget",
    "taxation",
    "prices",
    "insurance",
    "family",
    "migration",
    "demography and population",
    "social framework",
    "social affairs",
    "culture and religion",
    "social protection",
    "health",
    "urban development and urban policy",
    "education",
    "teaching",
    "organisation of teaching",
    "documentation",
    "communications",
    "information and information processing",
    "information technology and data processing",
    "natural and applied sciences",
    "humanities",
    "business organisation",
    "business classification",
    "legal form of organisations",
    "management",
    "accounting, commerce and company law",
    "competition",
    "employment",
    "labour market",
    "organisation of work and working conditions",
    "personnel management and staff remuneration",
    "labour law and labour relations",
    "transport policy",
    "organisation of transport",
    "land transport",
    "maritime and inland waterway transport",
    "air and space transport",
    "environmental policy",
    "natural environment",
    "deterioration of the environment",
    "agricultural policy",
    "agricultural structures and production",
    "farming systems",
    "cultivation of agricultural land",
    "means of agricultural production",
    "agricultural activity",
    "forestry",
    "fisheries",
    "plant product",
    "animal product",
    "processed agricultural produce",
    "beverages and sugar",
    "foodstuff",
    "soft drink",
    "production",
    "technology and technical regulations",
    "research and intellectual property",
    "energy policy",
    "coal and mining industries",
    "oil industry",
    "electrical and nuclear industries",
    "soft energy",
    "industrial structures and policy",
    "chemistry",
    "iron, steel and other metal industries",
    "mechanical engineering",
    "electronics and electrical engineering",
    "building and public works",
    "wood industry",
    "leather and textile industries",
    "miscellaneous industries",
    "Europe",
    "regions of EU Member States",
    "America",
    "Africa",
    "Asia and Oceania",
    "political geography",
    "overseas countries and territories",
    "United Nations",
    "European organisations",
    "extra-European organisations",
    "world organisations"
]

SEEDS_AI_DATA_FOCUSED = [
    # === CORE AI/DATA CONCEPTS ===
    "artificial intelligence",
    "machine learning",
    "algorithmic decision-making",
    "automated decision-making",
    "AI system",
    "high-risk AI system",
    
    # === DATA GOVERNANCE ===
    "data protection",
    "personal data",
    "data processing",
    "data subject",
    "data controller",
    "data processor",
    "data governance",
    "data sharing",
    "data intermediary",
    "data altruism",
    
    # === RIGHTS & OBLIGATIONS ===
    "rights and freedoms",
    "fundamental rights",
    "privacy rights",
    "right to explanation",
    "transparency obligation",
    "accountability",
    
    # === TECHNICAL/OPERATIONAL ===
    "technical documentation",
    "conformity assessment",
    "risk management",
    "human oversight",
    "accuracy requirement",
    "cybersecurity",
    "data quality",
    
    # === REGULATORY ===
    "supervisory authority",
    "enforcement",
    "compliance",
    "sanctions",
    "certification",
    
    # === SPECIFIC CONTEXTS ===
    "biometric identification",
    "emotion recognition",
    "critical infrastructure"
]

SEEDS_AI_DATA_FOCUSED_v2 = [
    # === CORE AI/DATA CONCEPTS ===
    "artificial intelligence",
    "machine learning",
    "algorithmic decision-making",
    "automated decision-making",
    "AI system",
    "high-risk AI system",

    # === DATA GOVERNANCE ===
    "data protection",
    "personal data",
    "data processing",
    "data subject",
    "data controller",
    "data processor",
    "data governance",
    "data sharing",
    "data intermediary",
    "data altruism",

    # === RIGHTS & OBLIGATIONS ===
    "rights and freedoms",
    "fundamental rights",
    "privacy rights",
    "right to explanation",
    "transparency obligation",
    "accountability",

    # === TECHNICAL/OPERATIONAL ===
    "technical documentation",
    "conformity assessment",
    "risk management",
    "human oversight",
    "accuracy requirement",
    "cybersecurity",
    "data quality",

    # === REGULATORY ===
    "supervisory authority",
    "enforcement",
    "compliance",
    "sanctions",
    "certification",

    # === SPECIFIC CONTEXTS ===
    "biometric identification",
    "emotion recognition",
    "critical infrastructure",

    # === AI ACT - SPECIFICI ===
    "general purpose AI",
    "GPAI",
    "foundation model",
    "systemic risk",
    "prohibited AI practice",
    "remote biometric identification",
    "AI literacy",
    "post-market monitoring",
    "deployer",
    "provider",
    "CE marking",
    "harmonised standard",
    "notified body",
    "AI regulatory sandbox",
    "real-world testing",

    # === DATA ACT - SPECIFICI ===
    "IoT device",
    "connected product",
    "data holder",
    "data recipient",
    "switching cost",
    "interoperability",
    "smart contract",
    "essential requirement",
    "unfair contractual term",
    "trade secret protection",

    # === DATA GOVERNANCE ACT - SPECIFICI ===
    "data altruism organization",
    "data cooperative",
    "data intermediation service",
    "consent management",
    "public sector body",
    "re-use of data",
    "single information point",
    "competent authority",

    # === GDPR - INTEGRATIVI ===
    "consent",
    "legitimate interest",
    "data minimization",
    "data accuracy",
    "purpose limitation",
    "storage limitation",
    "security of processing",
    "data portability",
    "right to erasure",
    "right to be forgotten",
    "data breach",
    "data protection impact assessment",
    "DPIA",
    "data protection officer",
    "DPO",
    "profiling",
    "special category data",
    "sensitive data",
    "cross-border processing",
    "lead supervisory authority",
    "one-stop-shop mechanism",
    "international data transfer",
    "transfer impact assessment",
    "standard contractual clauses",
    "adequacy decision",
    "binding corporate rules",
    "joint controller",
    "records of processing activities",
    "data protection by design",
    "data protection by default",

    # === TRASVERSALI - CONCETTI CHIAVE ===
    "lawfulness of processing",
    "fairness principle",
    "automated profiling",
    "safeguard measure",
    "redress mechanism",
    "market surveillance",
    "standardization",
    "incident reporting",
    "auditability",
    "traceability",
    "robustness",
    "record keeping",
    "vulnerability assessment",

    # === SETTORI/CONTESTI APPLICATIVI ===
    "healthcare application",
    "financial service",
    "employment context",
    "education and training",
    "law enforcement",
    "migration and border control",
    "administration of justice",
]